x-app: &app
  build: .
  volumes: ['.:/app']
  environment:
    - DATABASE_URL=postgres://postgres:postgres@db:5432/symmy_task
    - CELERY_BROKER_URL=redis://redis:6379/0
    - CELERY_RESULT_BACKEND=redis://redis:6379/1
    - POSTGRES_HOST=db
    - POSTGRES_DB=symmy_task
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
  depends_on:
    db:
      condition: service_healthy
    redis:
      condition: service_healthy

services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=symmy_task
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d symmy_task"]
      interval: 3s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 10

  web:
    <<: *app
    command: sh -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"

  worker:
    <<: *app
    command: celery -A core worker --loglevel=info

  beat:
    <<: *app
    command: celery -A core beat --loglevel=info
