# Generated by Django 5.2.14 on 2026-05-15 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrator', '0002_sync_state_recovery_and_quarantine_constraint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuarantinedProduct',
        ),
        migrations.RemoveField(
            model_name='productsyncstate',
            name='create_in_progress',
        ),
    ]
